const galleryAssetPath = (category, fileName) =>
  encodeURI(`assets/gallery/${category}/${fileName}`);

const galleryWebpAssetPath = (assetPath) =>
  assetPath.replace(/\.(png|jpe?g)$/i, '.webp');

const galleryThumbPath = (category, fileName) => {
  const baseName = fileName.replace(/\.[^.]+$/, '');
  return encodeURI(`assets/gallery/thumbs/${category}/${baseName}-thumb.webp`);
};

const galleryItems = [
  {
    id: 'field-1',
    type: 'image',
    category: ['field'],
    title: 'Woman Stranded on Rooftop Requesting Rescue',
    caption: 'Field report showing a resident trapped on a rooftop during severe flooding conditions.',
    thumb: galleryThumbPath('field', 'Babaeng na-trap sa bubong, humihingi ng tulong.png'),
    full: galleryAssetPath('field', 'Babaeng na-trap sa bubong, humihingi ng tulong.png'),
    alt: 'Woman stranded on a rooftop asking for help during flooding',
  },
  {
    id: 'field-2',
    type: 'image',
    category: ['field'],
    title: 'Barangay Command Center in Action',
    caption: 'Local command post coordinating response activity at the barangay level.',
    thumb: galleryThumbPath('field', 'Barangay command center in action.png'),
    full: galleryAssetPath('field', 'Barangay command center in action.png'),
    alt: 'Barangay command center coordinating response operations',
  },
  {
    id: 'field-3',
    type: 'image',
    category: ['field'],
    title: 'Barangay Health Worker Handling Medical Cases',
    caption: 'Frontline health support responding to urgent cases during an active incident.',
    thumb: galleryThumbPath('field', 'Barangay health worker handling medical cases.png'),
    full: galleryAssetPath('field', 'Barangay health worker handling medical cases.png'),
    alt: 'Barangay health worker handling medical cases during emergency response',
  },
  {
    id: 'field-4',
    type: 'image',
    category: ['field'],
    title: 'Calamity Response Featured on Live News',
    caption: 'Emergency response activity documented through a live news coverage context.',
    thumb: galleryThumbPath('field', 'Calamity response coverage on live news.png'),
    full: galleryAssetPath('field', 'Calamity response coverage on live news.png'),
    alt: 'Calamity response activity shown through live news coverage',
  },
  {
    id: 'field-5',
    type: 'image',
    category: ['field'],
    title: 'Cebu City EOC in Action',
    caption: 'Emergency Operations Center staff consolidating reports and coordinating decisions.',
    thumb: galleryThumbPath('field', 'Cebu City EOC in action.png'),
    full: galleryAssetPath('field', 'Cebu City EOC in action.png'),
    alt: 'Cebu City Emergency Operations Center in action',
  },
  {
    id: 'field-6',
    type: 'image',
    category: ['field'],
    title: 'Disaster Response in Barangay Sampaguita',
    caption: 'Community-level disaster response activity under barangay coordination.',
    thumb: galleryThumbPath('field', 'Disaster response in Barangay Sampaguita.png'),
    full: galleryAssetPath('field', 'Disaster response in Barangay Sampaguita.png'),
    alt: 'Disaster response activity in Barangay Sampaguita',
  },
  {
    id: 'field-7',
    type: 'image',
    category: ['field'],
    title: 'Emergency Response Coordination in Progress',
    caption: 'Responders aligning field information and operational tasks during an active incident.',
    thumb: galleryThumbPath('field', 'Emergency response coordination in progress.png'),
    full: galleryAssetPath('field', 'Emergency response coordination in progress.png'),
    alt: 'Emergency response coordination in progress',
  },
  {
    id: 'field-8',
    type: 'image',
    category: ['field'],
    title: 'EOC Integrates Starlink for Rapid Reports',
    caption: 'Connectivity support used to move field reports quickly into the operations center.',
    thumb: galleryThumbPath('field', 'EOC integrates Starlink for rapid reports.png'),
    full: galleryAssetPath('field', 'EOC integrates Starlink for rapid reports.png'),
    alt: 'Emergency Operations Center integrating Starlink for rapid reporting',
  },
  {
    id: 'field-9',
    type: 'image',
    category: ['field'],
    title: 'EOC Monitoring with Starlink Connectivity',
    caption: 'Operations staff monitoring emergency information with restored backhaul connectivity.',
    thumb: galleryThumbPath('field', 'EOC monitoring with Starlink connectivity.png'),
    full: galleryAssetPath('field', 'EOC monitoring with Starlink connectivity.png'),
    alt: 'EOC monitoring emergency information with Starlink connectivity',
  },
  {
    id: 'field-10',
    type: 'image',
    category: ['field'],
    title: 'Evacuation Center Registration in Progress',
    caption: 'Evacuee intake and registration process during shelter operations.',
    thumb: galleryThumbPath('field', 'Evacuation center registration in progress.png'),
    full: galleryAssetPath('field', 'Evacuation center registration in progress.png'),
    alt: 'Evacuation center registration in progress',
  },
  {
    id: 'field-11',
    type: 'image',
    category: ['field'],
    title: 'Governor Pam Leads Cebu EOC Meeting I',
    caption: 'Leadership coordination meeting inside the Cebu Emergency Operations Center.',
    thumb: galleryThumbPath('field', 'Governor Pam leads Cebu EOC meeting_1.png'),
    full: galleryAssetPath('field', 'Governor Pam leads Cebu EOC meeting_1.png'),
    alt: 'Governor Pam leading a Cebu EOC meeting',
  },
  {
    id: 'field-12',
    type: 'image',
    category: ['field'],
    title: 'Governor Pam Leads Cebu EOC Meeting II',
    caption: 'Follow-up operational coordination scene from the Cebu EOC.',
    thumb: galleryThumbPath('field', 'Governor Pam leads Cebu EOC meeting_2.png'),
    full: galleryAssetPath('field', 'Governor Pam leads Cebu EOC meeting_2.png'),
    alt: 'Second Cebu EOC meeting led by Governor Pam',
  },
  {
    id: 'field-13',
    type: 'image',
    category: ['field'],
    title: 'Landslide Alert on Barangay Road',
    caption: 'Roadside hazard alert affecting access and mobility in a barangay area.',
    thumb: galleryThumbPath('field', 'Landslide alert in barangay road.png'),
    full: galleryAssetPath('field', 'Landslide alert in barangay road.png'),
    alt: 'Landslide alert affecting a barangay road',
  },
  {
    id: 'field-14',
    type: 'image',
    category: ['field'],
    title: 'Landslide Rescue Operation in Progress',
    caption: 'Rescue activity underway in response to a landslide incident.',
    thumb: galleryThumbPath('field', 'Landslide rescue operation in progress.png'),
    full: galleryAssetPath('field', 'Landslide rescue operation in progress.png'),
    alt: 'Landslide rescue operation in progress',
  },
  {
    id: 'field-15',
    type: 'image',
    category: ['field'],
    title: 'Mayor Archival Addresses Media at EOC',
    caption: 'Leadership briefing and media communication from the emergency operations center.',
    thumb: galleryThumbPath('field', 'Mayor Archival addresses media at EOC.png'),
    full: galleryAssetPath('field', 'Mayor Archival addresses media at EOC.png'),
    alt: 'Mayor Archival addressing the media at the EOC',
  },
  {
    id: 'field-16',
    type: 'image',
    category: ['field'],
    title: 'Mayor Monitoring Emergency Dashboard Updates',
    caption: 'Executive oversight of live response information and dashboard activity.',
    thumb: galleryThumbPath('field', 'Mayor monitoring emergency dashboard updates.png'),
    full: galleryAssetPath('field', 'Mayor monitoring emergency dashboard updates.png'),
    alt: 'Mayor monitoring updates on an emergency dashboard',
  },
  {
    id: 'field-17',
    type: 'image',
    category: ['field'],
    title: 'Flood Report from Lusaran',
    caption: 'Example of a flood situation being reported from the field.',
    thumb: galleryThumbPath('field', 'Pag-report ng baha sa Lusaran.png'),
    full: galleryAssetPath('field', 'Pag-report ng baha sa Lusaran.png'),
    alt: 'Flood report from Lusaran',
  },
  {
    id: 'field-18',
    type: 'image',
    category: ['field'],
    title: 'Setting Up an Indoor Barangay Command Center',
    caption: 'Indoor command-center setup for local coordination during an incident.',
    thumb: galleryThumbPath('field', 'Pag-setup ng command center ng barangay_indoor.png'),
    full: galleryAssetPath('field', 'Pag-setup ng command center ng barangay_indoor.png'),
    alt: 'Indoor setup of a barangay command center',
  },
  {
    id: 'field-19',
    type: 'image',
    category: ['field'],
    title: 'Setting Up an Outdoor Barangay Command Center',
    caption: 'Outdoor command-center setup supporting field operations in difficult conditions.',
    thumb: galleryThumbPath('field', 'Pag-setup ng command center ng barangay_outdoor.png'),
    full: galleryAssetPath('field', 'Pag-setup ng command center ng barangay_outdoor.png'),
    alt: 'Outdoor setup of a barangay command center',
  },
  {
    id: 'field-20',
    type: 'image',
    category: ['field'],
    title: 'Updating the Status of Missing Persons',
    caption: 'Operational workflow for tracking and updating missing-person status.',
    thumb: galleryThumbPath('field', 'Pag-update ng status ng nawawala.png'),
    full: galleryAssetPath('field', 'Pag-update ng status ng nawawala.png'),
    alt: 'Updating the status of missing persons',
  },
  {
    id: 'field-21',
    type: 'image',
    category: ['field'],
    title: 'Reporting a Road Accident',
    caption: 'Incident reporting workflow for a traffic or roadway emergency.',
    thumb: galleryThumbPath('field', 'Pag-uulat ng aksidente sa kalsada.png'),
    full: galleryAssetPath('field', 'Pag-uulat ng aksidente sa kalsada.png'),
    alt: 'Reporting a road accident',
  },
  {
    id: 'field-22',
    type: 'image',
    category: ['field'],
    title: 'Reporting the Operational Situation',
    caption: 'Field-to-operations reporting flow for current response conditions.',
    thumb: galleryThumbPath('field', 'Pag-uulat ng sitwasyon sa operasyon.png'),
    full: galleryAssetPath('field', 'Pag-uulat ng sitwasyon sa operasyon.png'),
    alt: 'Reporting the operational situation',
  },
  {
    id: 'field-23',
    type: 'image',
    category: ['field'],
    title: 'Reporting a Fire Using Bantay Bayan',
    caption: 'Example fire-incident report captured through the Bantay Bayan workflow.',
    thumb: galleryThumbPath('field', 'Pag-uulat ng sunog gamit ang Bantay Bayan.png'),
    full: galleryAssetPath('field', 'Pag-uulat ng sunog gamit ang Bantay Bayan.png'),
    alt: 'Reporting a fire using Bantay Bayan',
  },
  {
    id: 'field-24',
    type: 'image',
    category: ['field'],
    title: 'Charging Devices During a Disaster',
    caption: 'Power continuity and charging support during disrupted conditions.',
    thumb: galleryThumbPath('field', 'Pagcha-charge sa gitna ng kalamidad.png'),
    full: galleryAssetPath('field', 'Pagcha-charge sa gitna ng kalamidad.png'),
    alt: 'Charging devices in the middle of a disaster',
  },
  {
    id: 'field-25',
    type: 'image',
    category: ['field'],
    title: 'Discussing the Disaster Situation Report',
    caption: 'Coordination meeting focused on reviewing and consolidating SITREP updates.',
    thumb: galleryThumbPath('field', 'Pagtalakay sa sitrep ng kalamidad.png'),
    full: galleryAssetPath('field', 'Pagtalakay sa sitrep ng kalamidad.png'),
    alt: 'Discussing the disaster situation report',
  },
  {
    id: 'field-26',
    type: 'image',
    category: ['field'],
    title: 'Receiving Relief Goods at the Barangay',
    caption: 'Relief intake and local handling at the barangay distribution point.',
    thumb: galleryThumbPath('field', 'Pagtanggap ng relief goods sa barangay.png'),
    full: galleryAssetPath('field', 'Pagtanggap ng relief goods sa barangay.png'),
    alt: 'Receiving relief goods at the barangay',
  },
  {
    id: 'field-27',
    type: 'image',
    category: ['field'],
    title: 'Receiving Evacuees During Heavy Rain in a Rural Area',
    caption: 'Shelter intake for evacuees under rural flood or storm conditions.',
    thumb: galleryThumbPath('field', 'Pagtanggap sa mga evacuee sa ulan_rural.png'),
    full: galleryAssetPath('field', 'Pagtanggap sa mga evacuee sa ulan_rural.png'),
    alt: 'Receiving evacuees during heavy rain in a rural area',
  },
  {
    id: 'field-28',
    type: 'image',
    category: ['field'],
    title: 'Receiving Evacuees During Heavy Rain in an Urban Area',
    caption: 'Urban shelter intake workflow during severe weather conditions.',
    thumb: galleryThumbPath('field', 'Pagtanggap sa mga evacuee sa ulan_urban.png'),
    full: galleryAssetPath('field', 'Pagtanggap sa mga evacuee sa ulan_urban.png'),
    alt: 'Receiving evacuees during heavy rain in an urban area',
  },
  {
    id: 'field-29',
    type: 'image',
    category: ['field'],
    title: 'Responding to a Looting Incident',
    caption: 'Public safety response to a security-related incident during crisis conditions.',
    thumb: galleryThumbPath('field', 'Pagtugon sa insidente ng looting.png'),
    full: galleryAssetPath('field', 'Pagtugon sa insidente ng looting.png'),
    alt: 'Responding to a looting incident',
  },
  {
    id: 'field-30',
    type: 'image',
    category: ['field'],
    title: 'Helping in a Time of Need',
    caption: 'Community-centered response support during an emergency.',
    thumb: galleryThumbPath('field', 'Pagtulong sa oras ng pangangailangan.png'),
    full: galleryAssetPath('field', 'Pagtulong sa oras ng pangangailangan.png'),
    alt: 'Helping in a time of need during emergency response',
  },
  {
    id: 'field-31',
    type: 'image',
    category: ['field'],
    title: 'Focused on Delivering Aid',
    caption: 'Field logistics and delivery work for relief distribution.',
    thumb: galleryThumbPath('field', 'Pagtutok sa paghatid ng tulong.png'),
    full: galleryAssetPath('field', 'Pagtutok sa paghatid ng tulong.png'),
    alt: 'Focused on delivering aid',
  },
  {
    id: 'field-32',
    type: 'image',
    category: ['field'],
    title: 'Monitoring Rising Water Levels',
    caption: 'Field monitoring activity tracking worsening flood conditions.',
    thumb: galleryThumbPath('field', 'Pagtutok sa tumataas na antas ng tubig.png'),
    full: galleryAssetPath('field', 'Pagtutok sa tumataas na antas ng tubig.png'),
    alt: 'Monitoring rising water levels',
  },
  {
    id: 'field-33',
    type: 'image',
    category: ['field'],
    title: 'Relief Distribution in Cebu',
    caption: 'Aid distribution activity supporting affected communities in Cebu.',
    thumb: galleryThumbPath('field', 'Pamamahagi ng ayuda sa Cebu.png'),
    full: galleryAssetPath('field', 'Pamamahagi ng ayuda sa Cebu.png'),
    alt: 'Relief distribution in Cebu',
  },
  {
    id: 'field-34',
    type: 'image',
    category: ['field'],
    title: 'Rescue Team Navigating Flooded Area',
    caption: 'Responders moving through flooded terrain to reach affected residents.',
    thumb: galleryThumbPath('field', 'Rescue team navigating flooded area.png'),
    full: galleryAssetPath('field', 'Rescue team navigating flooded area.png'),
    alt: 'Rescue team navigating a flooded area',
  },
  {
    id: 'field-35',
    type: 'image',
    category: ['field'],
    title: 'Trapped and Seeking Help During Landslide',
    caption: 'Emergency condition showing a resident in need during a landslide incident.',
    thumb: galleryThumbPath('field', 'Trapped and seeking help during landslide.png'),
    full: galleryAssetPath('field', 'Trapped and seeking help during landslide.png'),
    alt: 'Resident trapped and seeking help during a landslide',
  },
  {
    id: 'field-36',
    type: 'image',
    category: ['field'],
    title: 'Volunteer Coordinating Relief Efforts in Warehouse',
    caption: 'Back-end logistics coordination supporting relief operations.',
    thumb: galleryThumbPath('field', 'Volunteer coordinating relief efforts in warehouse.png'),
    full: galleryAssetPath('field', 'Volunteer coordinating relief efforts in warehouse.png'),
    alt: 'Volunteer coordinating relief efforts in a warehouse',
  },
  {
    id: 'screenshots-1',
    type: 'image',
    category: ['screenshots'],
    title: 'Emergency Hotline Operator Dashboard',
    caption: 'Application screenshot showing the operator-facing dashboard interface.',
    thumb: galleryThumbPath('screenshots', 'Emergency Hotline Operator Dashboard.png'),
    full: galleryAssetPath('screenshots', 'Emergency Hotline Operator Dashboard.png'),
    alt: 'Emergency Hotline operator dashboard screenshot',
  },
  {
    id: 'screenshots-2',
    type: 'image',
    category: ['screenshots'],
    title: 'Incident Details Page',
    caption: 'Application screenshot showing detailed incident information and workflow context.',
    thumb: galleryThumbPath('screenshots', 'Incident Details Page.png'),
    full: galleryAssetPath('screenshots', 'Incident Details Page.png'),
    alt: 'Incident details page screenshot',
  },
  {
    id: 'screenshots-3',
    type: 'image',
    category: ['screenshots'],
    title: 'PBB HQ Managing Regional Deployments',
    caption: 'HQ interface for monitoring and managing deployment activity at the regional level.',
    thumb: galleryThumbPath('screenshots', 'PBB  HQ - Managing Regional Deployments.png'),
    full: galleryAssetPath('screenshots', 'PBB  HQ - Managing Regional Deployments.png'),
    alt: 'PBB HQ interface for managing regional deployments',
  },
  {
    id: 'screenshots-4',
    type: 'image',
    category: ['screenshots'],
    title: 'PBB HQ Managing Barangay Deployments',
    caption: 'HQ deployment-management screen focused on barangay-level rollout visibility.',
    thumb: galleryThumbPath('screenshots', 'PBB HQ - Managing Barangay Deployments.png'),
    full: galleryAssetPath('screenshots', 'PBB HQ - Managing Barangay Deployments.png'),
    alt: 'PBB HQ interface for managing barangay deployments',
  },
  {
    id: 'screenshots-5',
    type: 'image',
    category: ['screenshots'],
    title: 'PBB HQ Managing Provincial Deployments',
    caption: 'HQ deployment-management screen focused on province-level rollout planning and tracking.',
    thumb: galleryThumbPath('screenshots', 'PBB HQ - Managing Provincial Deployments.png'),
    full: galleryAssetPath('screenshots', 'PBB HQ - Managing Provincial Deployments.png'),
    alt: 'PBB HQ interface for managing provincial deployments',
  },
  {
    id: 'hardware-1',
    type: 'image',
    category: ['hardware'],
    title: 'Mini Server Test',
    caption: 'Hardware validation view for a compact local server setup used in the node kit.',
    thumb: galleryThumbPath('hardware', 'Mini Server Test.png'),
    full: galleryAssetPath('hardware', 'Mini Server Test.png'),
    alt: 'Mini server hardware test',
  },
  {
    id: 'hardware-2',
    type: 'image',
    category: ['hardware'],
    title: 'Node Kit Case',
    caption: 'Protective carry case prepared for PBB node-kit deployment.',
    thumb: galleryThumbPath('hardware', 'Node Kit Case.png'),
    full: galleryAssetPath('hardware', 'Node Kit Case.png'),
    alt: 'Node kit case',
  },
  {
    id: 'hardware-3',
    type: 'image',
    category: ['hardware'],
    title: 'Node Kit Package Test Run',
    caption: 'Test run of the packed node kit before field deployment.',
    thumb: galleryThumbPath('hardware', 'Node Kit Package Test Run.png'),
    full: galleryAssetPath('hardware', 'Node Kit Package Test Run.png'),
    alt: 'Node kit package test run',
  },
  {
    id: 'hardware-4',
    type: 'image',
    category: ['hardware'],
    title: 'Node Kit Package with Mini Display',
    caption: 'Packed node kit including a compact display for quick setup and monitoring.',
    thumb: galleryThumbPath('hardware', 'Node Kit package with Mini Display.png'),
    full: galleryAssetPath('hardware', 'Node Kit package with Mini Display.png'),
    alt: 'Node kit package with mini display',
  },
  {
    id: 'hardware-5',
    type: 'image',
    category: ['hardware'],
    title: 'Node Kit Case with Server Components',
    caption: 'Packed deployment case showing the core server components of the node kit.',
    thumb: galleryThumbPath('hardware', 'Node Kit with Case with Server Components .png'),
    full: galleryAssetPath('hardware', 'Node Kit with Case with Server Components .png'),
    alt: 'Node kit case with server components',
  },
  {
    id: 'behind-1',
    type: 'image',
    category: ['behind'],
    title: 'CVISNET Aligns with PBB Infrastructure',
    caption: 'Behind-the-scenes collaboration around infrastructure alignment and project direction.',
    thumb: galleryThumbPath('behind', 'CVISNET aligns with PBB infrastructure.jpg'),
    full: galleryAssetPath('behind', 'CVISNET aligns with PBB infrastructure.jpg'),
    alt: 'CVISNET aligning with PBB infrastructure',
  },
  {
    id: 'behind-2',
    type: 'image',
    category: ['behind'],
    title: 'CVISNET Meeting to Join the PBB Consortium',
    caption: 'Consortium discussion focused on participation and collaboration within PBB.',
    thumb: galleryThumbPath('behind', 'CVISNET meeting to join PBB Consortium.jpg'),
    full: galleryAssetPath('behind', 'CVISNET meeting to join PBB Consortium.jpg'),
    alt: 'CVISNET meeting to join the PBB Consortium',
  },
  {
    id: 'behind-3',
    type: 'image',
    category: ['behind'],
    title: 'Demo Day Discussion on the Emergency Hotline System',
    caption: 'Product and operational discussion during a demo-day session.',
    thumb: galleryThumbPath('behind', 'Demo day discussions of use of Emergency Hotline System.jpg'),
    full: galleryAssetPath('behind', 'Demo day discussions of use of Emergency Hotline System.jpg'),
    alt: 'Demo day discussion on the Emergency Hotline System',
  },
  {
    id: 'behind-4',
    type: 'image',
    category: ['behind'],
    title: 'Demo Day for the Emergency Hotline System',
    caption: 'Public-facing or stakeholder-facing demonstration of the Emergency Hotline System.',
    thumb: galleryThumbPath('behind', 'Demo day of Emergency Hotline System.jpg'),
    full: galleryAssetPath('behind', 'Demo day of Emergency Hotline System.jpg'),
    alt: 'Demo day for the Emergency Hotline System',
  },
  {
    id: 'behind-5',
    type: 'image',
    category: ['behind'],
    title: 'Demo Day Operator Dashboard',
    caption: 'Operator dashboard presentation during a demo-day session.',
    thumb: galleryThumbPath('behind', 'Demo day operator dashboard.jpg'),
    full: galleryAssetPath('behind', 'Demo day operator dashboard.jpg'),
    alt: 'Demo day operator dashboard',
  },
  {
    id: 'behind-6',
    type: 'image',
    category: ['behind'],
    title: 'Demo Day Operator Demonstration',
    caption: 'Live operator workflow demonstration during a project showcase.',
    thumb: galleryThumbPath('behind', 'Demo day operator demonstration.jpg'),
    full: galleryAssetPath('behind', 'Demo day operator demonstration.jpg'),
    alt: 'Demo day operator demonstration',
  },
  {
    id: 'behind-7',
    type: 'image',
    category: ['behind'],
    title: 'Demo Day Showcases the Emergency Hotline System',
    caption: 'Event capture from a showcase focused on the Emergency Hotline System.',
    thumb: galleryThumbPath('behind', 'Demo day showcases Emergency Hotline System.jpg'),
    full: galleryAssetPath('behind', 'Demo day showcases Emergency Hotline System.jpg'),
    alt: 'Demo day showcasing the Emergency Hotline System',
  },
  {
    id: 'team-1',
    type: 'image',
    category: ['team'],
    title: 'First Team Meeting',
    caption: 'Early team alignment session around project direction and execution.',
    thumb: galleryThumbPath('team', '1st Team Meeting.jpg'),
    full: galleryAssetPath('team', '1st Team Meeting.jpg'),
    alt: 'First team meeting for the project',
  },
  {
    id: 'team-2',
    type: 'image',
    category: ['team'],
    title: 'CTU Joins the PBB Consortium',
    caption: 'Team and institutional alignment around consortium participation.',
    thumb: galleryThumbPath('team', 'CTU to join the PBB Consortium.jpg'),
    full: galleryAssetPath('team', 'CTU to join the PBB Consortium.jpg'),
    alt: 'CTU joining the PBB Consortium',
  },
  {
    id: 'team-3',
    type: 'image',
    category: ['team'],
    title: 'Signing of Commitment to Jump-start the PBB Consortium',
    caption: 'Formal commitment moment supporting the start of the PBB consortium effort.',
    thumb: galleryThumbPath('team', 'Signing of Commitment to Jump start the PBB Consortium.jpg'),
    full: galleryAssetPath('team', 'Signing of Commitment to Jump start the PBB Consortium.jpg'),
    alt: 'Signing of commitment to jump-start the PBB Consortium',
  },
];

galleryItems.forEach((item) => {
  if (item.type !== 'image' || !item.full) return;
  item.fullFallback = item.full;
  item.fullWebp = galleryWebpAssetPath(item.full);
});

const curatedGalleryOrder = [
  'field-5',
  'field-2',
  'screenshots-1',
  'hardware-4',
  'field-33',
  'behind-4',
  'field-8',
  'screenshots-4',
  'hardware-5',
  'field-34',
  'team-3',
  'field-10',
  'behind-6',
  'screenshots-5',
  'field-11',
  'hardware-1',
  'field-26',
  'behind-2',
  'team-1',
  'field-1',
  'screenshots-3',
  'hardware-2',
  'field-14',
  'behind-5',
  'team-2',
];

const curatedOrderIndex = new Map(
  curatedGalleryOrder.map((id, index) => [id, index])
);

galleryItems.sort((a, b) => {
  const aIndex = curatedOrderIndex.has(a.id) ? curatedOrderIndex.get(a.id) : Number.MAX_SAFE_INTEGER;
  const bIndex = curatedOrderIndex.has(b.id) ? curatedOrderIndex.get(b.id) : Number.MAX_SAFE_INTEGER;

  if (aIndex !== bIndex) {
    return aIndex - bIndex;
  }

  return a.id.localeCompare(b.id);
});

